trezor/trezor-crypto

rand.c
rand.h

Hi,
I've been carrying some patches I haven't had time to clean up and offer upstream, and I need to do something about that. This one is easy and non-invasive, just a trivial patch to allow a program to close the /dev/urandom file descriptor. The reason for this is that valgrind detects the open resource and thinks it's a leak even though it obviously isn't, and I like to keep the output of my test tools very clean so that any new problems jump out at me--otherwise I might miss them among the "expected failures."

Finalize all open file descriptors

---

ecdsa.c

The standard says:
step h:
```
Set T to the empty sequence.
while tlen < qlen
V = HMAC_K(V)
T = T || V
k = bits2int(T)
```
in this case (HMAC-SHA256, qlen=256bit) this simplifies to
```
V = HMAC_K(V)
T = V
k = bits2int(T)
```
and T can be omitted.
The old code (wrong) did:
```
T = HMAC_K(V)
k = bits2int(T)
```
Note that V will only be used again if the first k is out of range.
Thus, the old code produced the right result with a very high probability.
*Disclaimer*: I didn't test this.  It is infeasible to write a test that triggers the case this patch fixes without changing the API (or completely breaking HMAC-SHA256). The existing tests still pass:
```
tests.c:495:P:rfc6979:test_rfc6979:0: Passed
```
*Note*: The code doesn't handle the case where r or s in the signature get 0 (probability …

Fix RFC6979 generation of k.

---

bip39.c
bip39.h
bip39_english.h

This makes the pointers to the words constant.  It moves 8kb from ram
to flash and also prevents them from accidental corruption.  It changes
the return type of mnemonic_wordlist() to reflect this change.  Everyone 
calling it should also change the type to `const char * const *`.
This means trezor-mcu requires a trivial change. 
Just replace `const char** wl` with `const char * const * wl` twice in `recovery.c`.

Make word list const

---

ecdsa.c

An invalid point may crash the implementation or, worse,
reveal information about the private key if used in a ECDH
context (e.g. cryptoMessageEn/Decrypt).
Therefore, check all user supplied points even if
USE_PUBKEY_VALIDATE is not set.
To improve speed, we don't check if the point lies in the
main group, since the secp256k1 curve does not have
any other subgroup.

Always check for validity in ecdsa_read_pubkey.

---

bip39.c
bip39.h

This could lead to a buffer overrun if the final 0 byte is written to `current_word[j]` after the loop.
Also document the limit of passphrase in mnemonic_to_seed.

Off by one error in word length.

---

ecdsa.c

Not a bug, but annoying enough ;-)

Typo fix in RFC6979 implementation

---

tests.c
tools/.gitignore
tools/Makefile
tools/README.md
tools/mksecptable.c

The first patch adds the program I used to generate the precomputed table.
The second patch adds more tests for `scalar_multiply` and `point_multiply`.  I also ran them with more iterations for several minutes.

Added more tests for new multiplications

---

ecdsa.c

Error codes were not being propagated, always returned as 0.

Change return value of ecdsa_sign_digest

---

TrezorCrypto.pyx
setup.py

I found two bugs while trying to compile Trezor Crypto using Cython. 
1. If I attempted a private CKD using a hardened index in Python, it caused an integer overflow error due to the size difference between signed Python and C integers.
2. The setup.py file was missing an import for the nist256p1.c file.

Fixed issues with Python files

---

test_curves.py

It should be named `test_mult_half`, since it tests `bn_mult_half()` function.

test_curves: fix test case name typo

---

bignum.c
bignum.h
bip32.c
ecdsa.c

This contains some bug fixes, since bn_addmod does no longer a bn_mod.  Otherwise, mainly more documention.
Describe normalized, partly reduced and reduced numbers.
Comment which function expects which kind of input.
Removed unused bn_bitlen.
Add bn_add that does not reduce.
Bug fix in ecdsa_validate_pubkey: bn_mod before bn_is_equal.
Bug fix in hdnode_private_ckd: bn_mod after bn_addmod.

Extended comments, new function bn_add, a bug fix.

---

tests.c

This bug fix sets the length of the derived key in the last test_pbkdf2_hmac_sha256 test to 40 bytes to fix a buffer overflow, which is caused by the call to the pbkdf2_hmac_sha256 function, on the memory reserved by the local variable k.

Fixes a bug in the test_pbkdf2_hmac_sha256 test.

---

bignum.c
bip32.c
bip32.h
ecdsa.c
ecdsa.h
nist256p1.c
nist256p1.h
secp256k1.c
secp256k1.h
tests.c

Use different keys for different curves.  
To generate the root node from seed, "Bitcoin seed" is used for secp256k1 and "Nist256p1 seed" for the NIST256p1 curve.  The private/public key derivation for NIST is fixed.

Multicurve

---

ecdsa.c
ecdsa.h

Moved the code from Trezor firmware to here for recovering the public key
when verifying a bitcoin message.  Fixed the signing and verification for
the unlikely case the r value overflows.

New function ecdsa_verify_recover

---

bip32.c
bip32.h
tests.c

I'm not completely happy with this pull request, but I opened it to be able to discuss this.
This pull request changes the API and needs more changes to trezor-mcu to work, see the corresponding pull request trezor/trezor-mcu#97.
The goal of this pull request is to reduce the number of times we compute the public key.  This is both for performance reasons and to reduce the side-channel risk. I'm confident that the current implementation is side-channel resistant but if we can avoid computing a public key, we should avoid it.  For example for u2f we currently compute 10 public keys, including the master public key for the nist256p hierarchy.  With this patch u2f only computes the R value of the signature from the private nonce.
Things I'm not happy with:
- Most functions on hdnode are no …

Compute pubkey only on demand.

---

bip39.c
hmac.c
hmac.h
pbkdf2.c
pbkdf2.h
sha2.c
sha2.h
tests.c

The old implementation needed six sha transformations per iterations:
- 2 for computing sha512 of seed,
- 2 for computing digests of ipads/opads,
- 2 for computing digests of intermediate hashes.
This implementation caches the results of the first four sha512 transforms and is three times faster.

Faster PBKDF2

---

.gitignore

trezor/trezor-mcu#104 refactors the Makefile to use dependency files.
Because this repository does not ignore these files, git marks the
submodule as dirty.

Add generated dependency files to .gitignore

---

bip32.c
bip32.h
ecdsa.c
ecdsa.h
tests.c

The new name of the function is `hdnode_get_ethereum_address`
and it gets a hdnode as input as opposed to a public key.  This
also avoids first computing the compressed public key and then
uncompressing it.
Test cases were adapted to work with new function.  The test-vectors
are the same as for bip32 and independently checked with an adhoc
python implementation.

Moved get_ethereum_address from ecdsa to bip32

---

CONTRIBUTORS
bignum.c
bignum.h
tests.c

This adds
- a few basic tests (read_be, write_be, equal) to build other bignum tests from.
- little endian read/write
- copy/duplicate

Bignum: add tests and support little endian mode

---

bip32.c
bip32.h
ecdsa.c
ecdsa.h
test-openssl.c
test_curves.py
test_speed.c
tests.c

This adds an is_canonic parameter to all sign functions.  This is a
callback that determines if a signature corresponds to some coin
specific rules.  It is used, e. g., by ethereum (where the recovery
byte must be 0 or 1, and not 2 or 3) and or steem signatures (which
require both r and s to be between 2^248 and 2^255).
This also separates the initialization and the step function of the
random number generator, making it easy to restart the signature
process with the next random number.
It also fixes the (very unlikely) case where the signature is invalid
because the r or s value is zero.  Previously the signing process
failed; now it just tries the next k value.

Reworked rfc6979 signing.

---

Makefile
base58.c
base58.h
options.h
tests.c

This pull requests adds three more methods to `base58` to format the public key in Graphene-based blockchains properly.
Basically, the only difference is that it uses `ripemd160` for the checksum instead of `SHA256d`.
The complete public key in graphene based blockchains is (later) prefixed with an identifying string (e.g. `BTS` for BitShares, `STM` for Steem)

Add basic Graphene support

---

bip32.c

The bip32 private key derivation used bn_addmod to handle
wrap around.  This was never sufficient as bn_addmod uses only
bn_fast_mod, so an additional bn_mod is necessary.  The bn_fast_mod
helped when bn_mod was not side-channel safe.  Now that bn_mod uses
constant time code, we can get rid of the unnecessary bn_fast_mod
step and use bn_add instead of bn_addmod.

Use bn_add instead of bn_addmod

---

ecdsa.c
ecdsa.h

Signing uses the bn_inverse function that is prone to side-channel
attacks.  We randomize its argument by multiplying it with a random
non-zero number.  At the end we multiply again by the same number to
cancel it out.
Changed `generate_k_random` to take the prime range as a second argument and
to return a non-zero number.  This function was previously only used
for (non-rfc6979) signing and is now used for side-channel protection.

Protect signing against side-channel attack

---

.travis.yml
CMakeLists.txt

This allows `TrezorCrypto` to be linked with by other CMake projects

CMakeLists: Allow use as a library

---

Makefile

`tests` binary didn't get linked:
https://github.com/libcheck/check/issues/60

Fix for subunit tests on Ubuntu > 16.04

---

bip32.c
bip32.h
gui/mainwindow.cpp
tests.c

`hdnode_serialize_public` and `hdnode_serialize_private` take an additional `version` argument in order to support key serialization for altcoins.

hdnode_serialize_* altcoin support

---

.travis.yml
check_mem.h
tests.c

This pull request marks secret data as uninitialized, which causes Memcheck to throw an error when a pointer expression, conditional jump or conditional move depends on the secret data. This allows verification that a function is constant-time, with respect to the secret data.
* Fixed `check_mem.h` for Check 0.11
* Added `MARK_SECRET_DATA` and `UNMARK_SECRET_DATA` to inform Valgrind should be handled in constant-time
* Added Valgrind to Travis CI
* Skip speed tests when running on Valgrind
* Split curve tests into individual tests (to reduce individual test case time)
* Added `MARK_SECRET_DATA` in `test_ed25519` and `test_ed25519_cosi` to verify `ed25519-donna` is constant-time

Constant-time verification with Valgrind

---

README.md
aes/aescrypt.c
base58.c
test_check.c

* Add `//-fallthrough` comments for GCC 7.1.1 `-Wimplicit-fallthrough` (the comments look better than `__attribute__((fallthrough));`
* Add lowercase tests for Base32 RFC4648 (the RFC alphabet is optimized and has special support for uppercase and lowercase)
* Mention custom alphabets for Base32 in `README.md`

Minor fixes

---

bignum.c
bignum.h
test_check.c

When `exponent == 0` and `trailing == false`, the only change from the old `bn_format` is that when `decimals == 0`, it does not include a decimal point or trailing zero.
Also, no intermediate buffer is used. The formatted string is written directly to the output buffer, starting from the right, then `memmove` is used to move it to the left.
Fixes #102

Add integer formatting, exponent and trailing zero support to bn_format

---

bignum.c
bignum.h
test_check.c

`bn_digitcount` used to use `bn_bitcount`. This would give the maximum digits, which would often be higher than the actual number. This would result in leading zeroes in `bn_format`.

Fix bn_digitcount

---

CMakeLists.txt
Makefile
aes/aeskey.c
aes/aestst.c
aes/aestst.h

From what I can tell, neither `v`, nor `ff` access `ss`, so this should be a suitable solution to the sequence point warnings.

Fix sequence point warning in AES implementation

---

Makefile
ecdsa.h
segwit_addr.c
segwit_addr.h
test_check.c
test_segwit.c

Added bech32 (code by Peter Wuille).
Adapted the unit tests to our library.

Bech32 (BIP173) address support

---

blake256.c
blake256.h

The old implementation from Monero had issues with certain combinations of `hasher_Update`. This implementation does not have these issues.

Replace Blake256 implementation with correct one

---

Makefile
bip32.c
bip32.h
nem.c
nem.h
test_check.c
test_speed.c

The real purpose of this change is to make it easier to include the library into other projects.

Makefile: simplify include path, move subdirs to where used in C files

---

Makefile
base58.c
bip32.c
bip32.h
ecdsa.c
ecdsa.h
hasher.c
hasher.h
nist256p1.c
script.c
secp256k1.c
test_check.c
test_openssl.c
test_speed.c
tools/xpubaddrgen.c

This allows us to finely control when to use a single hash or a double hash in
various places. For example, Bitcoin signatures use double SHA256, but Decred
signatures use a single BLAKE256. However, both use double hashes for Base58.

Replace hasher_Double with HASHER_*D

---

bip32.c
bip32.h

After merged this can be removed from mcu https://github.com/trezor/trezor-mcu/blob/master/firmware/nem2.c#L267-L269
cc @saleemrashid

bip32/nem: IV is copied before encryption

---

bip32.c
options.h

I wanted to compile without all the 25519 curve stuff, so I had to add this configuration value.

bip32, options: optionally exclude 25519 curves in BIP32 support

---

Makefile
cash_addr.c
cash_addr.h
ecdsa.h
test_cashaddr.c
test_check.c

The new bitcoincash address format.
It is distinct from bech32 in several points:
- not limited to at most 90 characters
- 8 character checksum instead of 6
- separator is ':' instead of '1'
- only low 5 bit of hrp is used in checksum
we limit it to at most 129 characters plus NUL terminator

Added cashaddr support

---

chacha20poly1305/rfc7539.c

According to RFC 7539 there's no padding when associated data or plaintext is a multiple of 16.

Fix RFC 7539 padding

---

ed25519-donna/curve25519-donna-32bit.c

Use only the safe conversion from uint8_t to uint32_t.
Actually, the ARM gcc-compiler is good enough to detect this pattern.

Fix unaligned uint32 access in curve25519

---

Makefile
tests/test_check.c

Allow to compile without Valgrind using
```bash
NO_VALGRIND=1 make
```
In some configurations having Valgrind functional can be a problem, e.g., OSX 10.13 (http://www.valgrind.org/downloads/current.html#current) which makes development and testing a bit problematic. Having the possibility to disable Valgrind check would be therefore nice.

Allow to compile without Valgrind

---

secp256k1.c

Standard decred software uses `Bitcoin seed` instead of `Decred seed` as the bip32 master key[1][2]. 
Ideally, trezor should use the same master key as standard decred software to allow better interoperability; in particular to allow users to import their trezor seed (after a small conversion) into standard decred software.
While this breaks any existing decred trezor wallets, no software has been officially released to allow using decred with trezor. Neither trezor web wallet nor any decred wallet has been released to the general public yet. We can also provide a recovery path for any outstanding trezor users that might have already used the recently released firmware 1.6.2 with mainnet decred coins.
We'll need to have this fix applied then wait for the next round of firmware updates to …

Fix decred bip32 name

---

ed25519-donna/ed25519-donna-impl-base.c

Double scalar multiplication returns fully valid ED point (Just one more multiplication).
- Makes further operations easier because many operations expect full point (with valid `T` coordinate), not the partial. 
- `ge25519_scalarmult_base_niels` already returns full point so it would make it more consistent
- Scalar multiplications perform a large number of `curve25519_mul`, typically `(64*const)`, one more before returning from the function is IMO small overhead.
- if `ge25519_scalarmult` returns partial point one cannot easily make it the full point because after `ge25519_scalarmult` returns, the temporary point is not accessible. To make it full point much more expensive inversion would be needed.
If you prefer not to add multiplication there is another alternative - a bit more …

ed25519: double scalarmult fix - return full point

---

ed25519-donna/ed25519-donna-impl-base.c

`ge25519_scalarmult` minor changes:
- Result `r` can be equal to the input `p1` (same point pointer).
- Returns fully valid extended Edwards point (not partial as before). 
- Makes further operations easier because many operations expect full point (with valid `T` coordinate), not the partial. 
- `ge25519_scalarmult_base_niels` already returns full point so it would make it more consistent
- Scalar multiplications perform large number of `curve25519_mul`, typically `(64*const)`, one more before returning from the function is IMO small overhead.
- if `ge25519_scalarmult` returns partial point one cannot easily make it full point because after `ge25519_scalarmult` returns, the temporary point is not not accessible. To make it full point much more expensive inversion would be needed.

ed25519: scalarmult fix so dst can be src

---

ed25519-donna/ge25519.c
ed25519-donna/ge25519.h
monero/xmr.c
tests/test_check.c
tests/test_check_monero.h

PR that came from the discussion with @onvej-sl in https://github.com/trezor/trezor-crypto/pull/169 
Requires rebasing on top of the master and merging https://github.com/trezor/trezor-crypto/pull/171 and https://github.com/trezor/trezor-crypto/pull/172 first.

Monero: normalization fixes

---

bip32.c
bip32.h
bip39.c
pbkdf2.c
pbkdf2.h
tests/test_check.c
tests/test_check_cardano.h

Added support for derivation scheme v2 in cardano.
V1 is mainly used in the official cardano wallet Daedalus and V2 is new derivation scheme used in project [Icarus](https://github.com/input-output-hk/project-icarus-chrome)
In this PR I made **potentially breaking change in implementation of pbkdf2** where I added support for variable key length as in cardano v2 is needed key of length 96 instead of 64
All tests are passing in this repository and also in trezor-core, trezor-crypto and python-trezor but I do not know which repositories could be affected by this.

Add support for cardano derivation scheme v2

---

ecdsa.c
ecdsa.h
tests/test_check.c

Changes the `ecdsa_verify_digest_recover` function to `ecdsa_recover_pub_from_sig`, to avoid confusion
Fix #180

Improve function naming
