tests.c
Pavol,
I apologize--I missed including this in the last patch. Sorry.
Dustin
=> Remove now-redundant embedded header

bignum.c
Added invariants for `bn_multiply` and `bn_inverse`.
Explain that `bn_multiply` and `bn_fast_mod` don't work for an arbitrary modulus.  The modulus must be close to 2^256.
This is a comment-only patch.  There are some not so nice things I would like to change, but I don't want to introduce new bugs.
1. The last `bn_fast_mod` call in `bn_inverse` is completely useless.
2. In most cases `bn_inverse` returns a number < prime, but not in the case prime=`prime256k1`, where it may be < 2 * prime (should `bn_fast_mod` be replaced by `bn_mod`?). No current caller relies on this.
3. `bn_substract` is a typo, should be `bn_subtract`.
4. The function `bn_substract` has very weird properties, especially the 2u * prime thing is strange (should it work with second argument < 2 * prime?  Also despite …
=> Added comments to the tricky algorithms.

base58.c, bignum.c, bip32.c, ecdsa.c, hmac.c, macro_utils.h, pbkdf2.c
I made sure to clear temp buffers before functions exited.
before my changes, private keys and all kinds of stuff could be just floating around in the stack.
=> Code Security change

.travis.yml
- use new container-based infrastructure
- build and run OpenSSL tests
- run NIST256P1 and SECP256K1 compatibility tests (against python-ecdsa package)
=> Improve Travis CI usage

ecdsa.c, test_curves.py
Minor simplification of test in jacobian_add.
Added unit test for bn_add.
Fixed unit tests for bn_addmod and bn_mult_half.
=> Fixed more unit tests.  Simplified jacobian_add

bignum.c, ecdsa.c, test_curves.py
Some points designed to test for underflow of x^3-ax.
=> Added more tests for specific points.

bip32.c, tests.c
Check for invalid curve name.
New test case for an invalid derivation (a hole in bip32) for the NIST curve.
=> Multicurve

CMakeLists.txt, Makefile, c.pxd, test_curves.py
Diffs to make the unit tests work again.
=> Updated cmake configuration for ed25519

ecdsa.c, tests.c
Added unit tests for `ecdsa_verify_digest_recover()`
=> Added Unit test, fixed one corner case.

CMakeLists.txt, Makefile, ecdsa.c, ecdsa.h, options.h, sha3.c, sha3.h, tests.c
Based on the discussion: https://github.com/trezor/trezor-common/pull/11
Comments welcome
=> Support Ethereum pubkeyhash

sha2.c
=> sha2: fix unaligned access.

gui/mainwindow.cpp
Does what it says on the tin! :)
=> Update GUI for newer HDNode API

ecdsa.c
=> ecdsa: fix out-of-bounds read in point_multiply

.travis.yml, CMakeLists.txt, Makefile, bip32.c, bip32.h, curve25519-donna/curve25519-donna.c, curve25519-donna/curve25519-donna.h, curves.c, curves.h, setup.py, test_curves.py
This should allow adding support for Curve25519 GPG decryption (see https://github.com/trezor/trezor-mcu/pull/120).
=> Add support for Curve25519-based ECDH

tests.c
=> tests: add BIP32 ECDH

test_curves.py
Following https://github.com/trezor/trezor-crypto/commit/0abc61f6722580ee779614ef5b31d17a29e4d841.
=> tests: fix curve25519 unittests

sha2.c, sha2.h, tests.c
Import of Aaron D. Gifford's SHA1 implementation. This is needed for calculation of OpenPGP fingerprints.
=> Add SHA1 implementation

ecdsa.c, tests.c
Use code from address.c in ecdsa.c
Added unit tests.
=> Removed duplicated code for multi-byte prefixes

bip32.c, bip32.h, test_speed.c
Changed signature of public_ckd_address_optimized to not include the
compressed public_key (uncompressed is in pub).
TODO: rerun emscripten
=> Refactored duplicated code

test_check.c
=> Constant-time verification for Ed25519

bip32.c
/cc @jhoenicke https://github.com/trezor/trezor-crypto/pull/101#discussion_r129148522
=> Fix NULL dereference in hdnode_from_xprv

Makefile
=> Add aestst to default Makefile goal

nem.h
It is broken and completely useless
=> Remove NEM_DECRYPTED_PAYLOAD_SIZE

rand.c
Change to using a CPP flag instead of new file.
=> rand.c: platform depedenant code can be removed using CPP flag

blake2b.c, blake2b.h, hasher.c
=> blake2b: Add init with personal key

address.c, address.h, tests/test_check.c
Based on [RSKIP-60](https://github.com/rsksmart/RSKIPs/blob/master/IPs/RSKIP60.md).
=> Implement RSKIP-60 checksum address encoding

Makefile, bip32.c, bip32.h, bip39.c, bip39.h, curves.c, curves.h, ed25519-donna/ed25519.c, ed25519-donna/ed25519.h, tests/test_check.c
This PR is for adding Cardano currency support and is intended to merge with https://github.com/trezor/trezor-core/pull/250
For the support of Cardano currency was required to add cardano-specific ed25519 crypto support.
The crypto code is based on [cardano-crypto](https://github.com/input-output-hk/cardano-crypto) and [cardano-sl](https://github.com/input-output-hk/cardano-sl) - official Cardano repos.
We are NOT official developers of Cardano, however we are developers of [www.cardanolite.com](https://www.cardanolite.com)
=> Add Cardano currency support

chacha20poly1305/chacha20poly1305.c, chacha20poly1305/chacha20poly1305.h, chacha20poly1305/rfc7539.c, chacha20poly1305/rfc7539.h
Fix counter initialization bug in rfc7539_init() and const correctness in rfc7539.h and chacha20poly1305.h.
=> Fix counter initialization bug in rfc7539_init() and const correctness.

rand.c
To increase period. See https://github.com/trezor/trezor-core/issues/440
=> switch to 'Numerical Recipes' constants and remove random8
